### PR TITLE
adapt changes in ghc 9.2

### PR DESCRIPTION
**Pull request by tek**
not very pretty, please suggest whatever you'd prefer

### CODE REVIEW

**Comment by tek** [comment]
@andrewthad @chessai anyone wanna merge this?

**Comment by chessai** [comment]
instead of CPP in multiple places, can we have an internal .Compat module which provides wrapper functions (marked inline), so that the CPP is all in one place?

Alternatively, we could depend on a compat library, if one exists (I think it does, but I can't recall)

**Comment by andrewthad** [comment]
In https://github.com/byteverse/bytesmith/pull/25, I've added a test for the `cstring` parser. The proposed changes in this PR break that parser. It should be possible to observe that by rebasing on top of master and building the test suite and running it. The fix is simple though. When reading from the pointer, you just need to use a read function that reads an 8-bit word.

As @chessai mentions, using `word-compat` might clean this up a bit. I'm not too worried about the CPP though because, once GHC 9.6 is out, I'll drop everything before 9.2, and then the whole transitional mess of word types and primops will be gone. If you fix the cstring parser, I'm fine with the rest of it as is. But if you want to switch it to use `word-compat`, that's fine too.

**Comment by tek** [comment]
In the meantime I rebased on `cstring` and adapted the code

**Comment by andrewthad** [comment]
This looks good. I just built with ghc 8.10.7, 9.0.2, and 9.2.3 and the test suite passes on all of them. Merging.

**Pull request merged**
